name: Go

on:
  release:
    types: [ published ]
  push:
    branches: [ master ]
    paths:
      - "scripts/**"
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/*.yml"
  pull_request:
    branches: [ master ]
    paths:
      - "scripts/**"
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/*.yml"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        goos: [windows, linux, darwin]
        goarch: [amd64, arm64]
        include:
        - goos: linux
          goarch: arm
          goarm: 7
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOARM: ${{ matrix.goarm }}

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Get asset filename
      id: get_filename
      run: echo "ASSET_NAME=$GOOS-$GOARCH$GOARM" >> "$GITHUB_OUTPUT"

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Build
      run: ./scripts/build.sh

    - name: Test
      if: matrix.goos == 'linux' && matrix.goarch == 'amd64'
      run: go test -v

    - name: Zip
      run: |
        cd build
        zip -vr m3u8-downloader-${{ steps.get_filename.outputs.ASSET_NAME }}.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v6
      with:
        name: m3u8-downloader-${{ steps.get_filename.outputs.ASSET_NAME }}
        path: build/m3u8-downloader-${{ steps.get_filename.outputs.ASSET_NAME }}.zip

  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    needs: build
    steps:
    - uses: actions/download-artifact@v7
      with:
        path: artifacts
        merge-multiple: true

    - name: Upload files to GitHub release
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/*
